### ISSUE TITLE
CC Mode with power limit not working

### ISSUE THREAD

**Issue by luroche** [WattRex/Battery-Cycler-Drivers#17]
```
Changing to CC_MODE DISCHARGE with POWER limit
Set ref in mA: -3000
Set limit in dW: -110
Traceback (most recent call last):
  File "tests/tests_limits.py", line 240, in <module>
    data.change_mode(mode, direction, limit)
  File "tests/tests_limits.py", line 74, in change_mode
    epc.set_cc_mode(ref, limit, lim)
  File "/.local/lib/python3.7/site-packages/battery_cycler_drv_epc/drv_epc.py", line 458, in set_cc_mode
    msg = DrvCanMessageC(addr= id_msg, size= 8, data = data_msg)
  File "/.local/lib/python3.7/site-packages/can_sniffer/can_sniffer.py", line 69, in __init__
    self.data = data.to_bytes(size, byteorder='little', signed = True)
OverflowError: int too big to convert
```

**Comment by RobertoAldea** [comment]
This can not work, as the control current can not have limit in current
